apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create/$', views.create, name="create"),
    url(r'^create_user/$', views.create_user, name="create_user"),
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^login/$', views.login, name="login"),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^register/$', views.register, name="register"),    
    url(r'^new/$', views.new, name="new"),    
    url(r'^remove/(?P<user_id>\d+)/$', views.remove, name="remove"),    
    url(r'^edit/(?P<user_id>\d+)/$', views.edit, name="edit"),
    url(r'^edit_personal_info/(?P<user_id>\d+)/$', views.edit_personal_info, name="edit_personal_info"),    
    url(r'^edit_passwords/(?P<user_id>\d+)/$', views.edit_passwords, name="edit_passwords"),
    url(r'^edit_description/(?P<user_id>\d+)/$', views.edit_description, name="edit_description"),
    url(r'^wall/$', views.wall, name="wall"),
    url(r'^message/$', views.message, name="message"),
    url(r'^(?P<message_id>\d+)/comment$', views.comment, name="comment"),
    url(r'^(?P<comment_id>\d+)/delete_comment$', views.delete_comment, name="delete_comment")
]

user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.main.urls', namespace = "users"))
]

apps/main/models.py
from django.db import models
import bcrypt
import re
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.


class UserManager(BaseUserManager):
    def validate(self, form):
        errors = []
        if len(form['first_name']) < 2:
            errors.append("First name must be at least 2 characters long.")

        if len(form['last_name']) < 2:
            errors.append("Last name must be at least 2 characters long.")

        if len(form['password']) < 8 & len(form['confirm_password']) < 8:
            errors.append("Password must be at least 8 characters long.")

        if not EMAIL_REGEX.match(form['email']):
            errors.append("Must be a valid email address.")

        if form['password'] != form['confirm_password']:
            errors.append("You need to confirm the password!")

        existing_email = User.objects.filter(email=form['email'])
        if existing_email:
            errors.append("Email already in use!")
            print(existing_email)

        return errors

    def easy_create(self, form):
        hashed_pw = bcrypt.hashpw(form['password'].encode(), bcrypt.gensalt())
        
        if len(User.objects.filter(is_admin=True)) == 0:            
            first_user = User.objects.create(
                first_name=form['first_name'],
                last_name=form['last_name'],
                email=form['email'],
                pw_hash=hashed_pw,
                is_admin=True,
                id=1
            )
            return first_user.id
        else:
            user = User.objects.create(
                first_name=form['first_name'],
                last_name=form['last_name'],
                email=form['email'],
                pw_hash=hashed_pw
            )

            return user.id


    def login(self, form):
        existing_user = User.objects.filter(email=form['email'])

        if existing_user:
            user = existing_user[0]
            if bcrypt.checkpw(form['password'].encode(), user.pw_hash.encode()):
                return(True, user.id)
        return(False, "Email or password incorrect!")


    def edit_personal_info(self, form, user_id):
        user = User.objects.get(id=user_id)
        print(user)
        # user_lev =form['user_level']
        if 'user_level' in form: 
            if form['user_level'] == 'admin':
                user.is_admin = True
                
            elif form['user_level'] == 'normal':
                user.is_admin = False
                
        user.first_name = form['first_name']
        user.last_name = form['last_name']
        user.email = form['email']
        user.save()
        return user


    def edit_passwords(self, form, user_id):
        user = User.objects.get(id=user_id)
        
        if form['password'] == form['confirm_password']:
            pw = bcrypt.hashpw(form['password'].encode(), bcrypt.gensalt())
            print(pw)
            user.pw_hash = pw
            user.save()
            return user
                           

    def edit_description(self, form, user_id):
        user = User.objects.get(id=user_id)

        user.description = form['description']
        user.save()
        return user
        

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=255)

    is_admin = models.BooleanField(default=False, null=False)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    objects = UserManager()

    def __repr__(self):
        return "<User: %s>" % self.first_name

    def __str__(self):
        return "<User: %s>" % self.first_name


class MessageManager(models.Manager):
    def create_message(self, form, user_id):
        message = Message.objects.create(
            message = form['message'],
            user = User.objects.get(id=user_id)
        )

        return message.id

class CommentManager(models.Manager):
    def create_comment(self, form, user_id, message_id):
        user = User.objects.get(id=user_id)
        message = Message.objects.get(id=message_id)
        comment = Comment.objects.create(
            comment = form['comment'],
            user = user,
            message = message
        )
        return comment.id



class Message(models.Model):
    message = models.TextField()
    user = models.ForeignKey(User, related_name="messages")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = MessageManager()

    def __repr__(self):
        return "<Message: %s>" % self.message

    def __str__(self):
        return "<Message: %s>" % self.message


class Comment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, related_name="comments")
    message = models.ForeignKey(Message, related_name="comments")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CommentManager()

    def __repr__(self):
        return "<Comment: %s>" % self.comment

    def __str__(self):
        return "<Comment: %s>" % self.comment

apps/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, Message, Comment
from django.core.urlresolvers import reverse

# Create your views here.


def index(request):
    if 'user_id' not in request.session:
        return render(request, 'main/index.html')

    return redirect('users:dashboard')


def create(request):
    print(request.POST)

    errors = User.objects.validate(request.POST)

    if errors:
        for error in errors:
            messages.error(request, error)

        return redirect('users:index')

    user_id = User.objects.easy_create(request.POST)
    request.session['user_id'] = user_id
    
    print('SESSION USER ID: ', request.session['user_id'])
    return redirect('users:dashboard')

def create_user(request):
    print("REQUEST POST: ",request.POST['first_name'])

    errors = User.objects.validate(request.POST)

    if errors:
        for error in errors:
            messages.error(request, error)

        return redirect('users:index')

    user_id = User.objects.easy_create(request.POST)
    print("NEW USER: ", user_id)
    return redirect('users:dashboard')


def dashboard(request):
    if 'user_id' not in request.session:
        return redirect('users:index')

    users_there = User.objects.all()
    if len(users_there) == 0:
        request.session.clear()
    else:
        is_user = request.session['user_id']

    if len(User.objects.filter(is_admin=True)) == 1:
        # is_admin = User.objects.get(is_admin=True)
        is_admin = User.objects.first()

    
        if is_user == is_admin.id:
            request.session['admin_id'] = is_admin.id
    elif len(User.objects.filter(is_admin=True)) > 1:
        pass

    if request.session['user_id']:
        context = {
            "user": User.objects.get(id=request.session['user_id']),
            "users": User.objects.all()
        }

        return render(request, 'main/dashboard.html', context)
    else:
        return render(request, 'main/index.html')

def logout(request):
    request.session.clear()
    return redirect('users:index')


def login(request):
    valid, result = User.objects.login(request.POST)

    if not valid:
        messages.error(request, result)
        return redirect('users:index')

    request.session['user_id'] = result
    return redirect('users:dashboard')


def signin(request):
    return render(request, 'main/signin.html')


def register(request):
    return render(request, 'main/register.html')


def new(request):
    context = {
        "user": User.objects.get(id=request.session['user_id'])
    }

    return render(request, 'main/add_new.html', context)


def remove(request, user_id):
    print("USER ID: -- remove ", user_id)
    # check if is admin
    user = User.objects.get(id=user_id)
    user.delete()
    return redirect('users:dashboard')



def edit(request, user_id):
    context = {
        "user": User.objects.get(id=request.session['user_id']),
        "edit_user": User.objects.get(id=user_id)
    }   
    return render(request, 'main/edit_user_info.html', context)



def edit_personal_info(request, user_id):
    print("Update mode: ", user_id)
    updated_user = User.objects.edit_personal_info(request.POST, user_id)
    return redirect(reverse('users:edit', kwargs={"user_id": updated_user.id}))
  
    
def edit_passwords(request, user_id):
    print("Update passwords mode: ", user_id)
    updated_password = User.objects.edit_passwords(request.POST, user_id)
    return redirect(reverse('users:edit', kwargs={"user_id": updated_password.id}))


def edit_description(request, user_id):
    updated_description = User.objects.edit_description(request.POST, user_id)
    return redirect(reverse('users:edit', kwargs={"user_id": updated_description.id}))



def wall(request):
    if 'user_id' not in request.session:
        return redirect('wall:index')

    context = {
        "user": User.objects.get(id=request.session['user_id']),
        "messages": Message.objects.order_by("-created_at"),
        "comments": Comment.objects.order_by("-created_at")
    }

    return render(request, 'main/wall.html', context)


def message(request):
    print("Message place:", request.POST['message'])
    user_id = request.session['user_id']
    Message.objects.create_message(request.POST, user_id)
    return redirect('users:wall')


def comment(request, message_id):

    print(request.POST)
    print("MESSAGE ID: ", message_id)
    request.session['message_id'] = message_id
    print("USER ID: ", request.session['user_id'])
    user_id = request.session['user_id']
    Comment.objects.create_comment(request.POST, user_id, message_id)
    
    return redirect('users:wall')
    

def delete_comment(request, comment_id):
    print("COMMENT ID:", comment_id)
    comm = Comment.objects.get(id=comment_id)
    print("COMMENT user ID:", comm.user.id)
    print("REQUEST SESSION USER ID: ", request.session['user_id'])
    admin = request.session['admin_id']
    if comm.user.id == request.session['user_id']:
            
        comment = Comment.objects.get(id=comment_id)
        comment.delete()
        return redirect(reverse('users:wall'))
    elif admin:
        comment = Comment.objects.get(id=comment_id)
        comment.delete()
        return redirect(reverse('users:wall'))
    else:
        return redirect(reverse('users:wall'))


        return redirect(reverse('users:wall'))

apps/main/templates/main/add_new.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>User Dashboard!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <h1 class="title">
        Add a new user
      </h1>

      <form action="{% url 'users:create_user' %}" method="POST">
        {% csrf_token %}
        <div class="field">
          <label class="label">First Name</label>
          <div class="control">
            <input class="input" name="first_name" type="text" placeholder="">
          </div>
        </div>
        <div class="field">
          <label class="label">Last Name</label>
          <div class="control">
            <input class="input" name="last_name" type="text" placeholder="">
          </div>
        </div>

        <div class="field">
          <label class="label">Username</label>
          <div class="control has-icons-left has-icons-right">
            <input class="input" name="username" type="text" placeholder="" value="">
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
            <span class="icon is-small is-right">
              <i class="fas fa-check"></i>
            </span>
          </div>
        </div>

        <div class="field">
          <label class="label">Email</label>
          <div class="control has-icons-left has-icons-right">
            <input class="input is-danger" name="email" type="email" placeholder="" value="hello@">
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
            <span class="icon is-small is-right">
              <i class="fas fa-exclamation-triangle"></i>
            </span>
          </div>
        </div>
        <div class="field">
          <label class="label">Password</label>
          <p class="control has-icons-left">
            <input class="input" name="password" type="password" placeholder="">
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </p>
        </div>
        <div class="field">
          <label class="label">Confirm Password</label>
          <p class="control has-icons-left">
            <input class="input" name="confirm_password" type="password" placeholder="">
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </p>
        </div>
        <input href="" class="button is-gray is-medium is-primary is-outlined" type="submit" value="Create" />
      </form>
    </section>
  </div>
</body>

</html>

apps/main/templates/main/dashboard.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>User Dashboard!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    </br>
    </br>
    <h1 class="title">
      Manage Users
      </br>
      </br>
      </br>
      {% if request.session.admin_id %}
      <a href="{% url 'users:new' %}" class="button is-gray is-small is-info is-outlined">Add New</a>
      {% endif %}
    </h1>
    <p class="title">

    </p>

    <table class="table">
      <thead>
        <tr>
          <th><abbr title="Position">ID</abbr></th>
          <th>Name</th>
          <th><abbr title="Played">Email</abbr></th>
          <th><abbr title="Won">Created at</abbr></th>
          <th><abbr title="Won">User Level</abbr></th>
          {% if request.session.admin_id %}
          <th><abbr title="Won">Actions</abbr></th>
          {% endif %}
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th><abbr title="Position">ID</abbr></th>
          <th>Name</th>
          <th><abbr title="Played">Email</abbr></th>
          <th><abbr title="Won">Created at</abbr></th>
          <th><abbr title="Won">User Level</abbr></th>
          {% if request.session.admin_id %}
          <th><abbr title="Won">Actions</abbr></th>
          {% endif %}
        </tr>
      </tfoot>
      <tbody>
        {% for user in users  %}
        <tr>
          <th>{{ user.id }}</th>
          {% if request.session.admin_id %}
            <td><a href="{% url 'users:edit' user.id %}" class="is-text">{{ user.first_name }} {{ user.last_name }} </a><strong>()</strong> </td>
          {% else %}
            <td><a class="is-text">{{ user.first_name }} {{ user.last_name }} </a><strong>()</strong> </td>
          {% endif %}
         
          <td>{{ user.email }}</td>
          <td>{{ user.created_at }}</td>
          {% if user.is_admin %}
            <td>Admin</td>
          {% else %}
            <td>User</td>

          {% endif %}

          {% if request.session.admin_id %}

          <td>
            <a href="{% url 'users:remove' user.id %}" class="button is-gray is-small is-outlined">Remove</a>
            <a href="{% url 'users:edit' user.id %}" class="button is-gray is-small is-outlined">Edit</a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</body>

</html>

apps/main/templates/main/edit_user_info.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>User Dashboard!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <h1 class="title">
        Edit {{ edit_user.first_name }}'s Profile!
        <a href="{% url 'users:dashboard' %}" class="button is-grey is-text">Back to dashboard</a>
      </h1>
      <div class="columns">
        <div class="column">
          <h1 class="subtitle">
            Edit Information
          </h1>
          <div class="box">
            <form action="{% url 'users:edit_personal_info' edit_user.id %}" method="POST">
              {% csrf_token %}
              <div class="field">
                <label class="label">Email</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="email" type="email" placeholder="Email input"
                    value="{{ edit_user.email }}">
                  <span class="icon is-small is-left">
                    <i class="fas fa-envelope"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-exclamation-triangle"></i>
                  </span>
                </div>
              </div>

              <div class="field">
                <label class="label">First Name</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="first_name" type="text" placeholder="" value="{{ edit_user.first_name }}">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-check"></i>
                  </span>
                </div>
              </div>
              <div class="field">
                <label class="label">Last Name</label>
                <div class="control has-icons-left has-icons-right">
                  <input class="input" name="last_name" type="text" placeholder="" value="{{ edit_user.last_name }}">
                  <span class="icon is-small is-left">
                    <i class="fas fa-user"></i>
                  </span>
                  <span class="icon is-small is-right">
                    <i class="fas fa-check"></i>
                  </span>
                </div>
              </div>

              {% if request.session.admin_id %}

              <div class="field">
                <label class="label">User Level</label>
                <div class="control">
                  <div class="select">
                    <select name="user_level">
                      {% if edit_user.is_admin %}
                      <option value="admin">Admin</option>
                      <option value="normal">Normal</option>
                      {% else %}
                      <option value="normal">Normal</option>
                      <option value="admin">Admin</option>
                      {% endif %}
                    </select>
                  </div>
                </div>
              </div>
              {% endif %}
              
              <input type="submit" class="button is-primary" value="Save" />
            </form>
          </div>

        </div>
        <div class="column">
          <h1 class="subtitle">
            Change Password
          </h1>

          <div class="box">
            <form action="{% url 'users:edit_passwords' edit_user.id %}" method="POST">
              {% csrf_token %}
              <div class="field">
                <label class="label">Password</label>
                <p class="control has-icons-left">
                  <input class="input" name="password" type="password" placeholder="Password">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <div class="field">
                <label class="label">Confirm Password</label>
                <p class="control has-icons-left">
                  <input class="input" name="confirm_password" type="password" placeholder="Confirm Password">
                  <span class="icon is-small is-left">
                    <i class="fas fa-lock"></i>
                  </span>
                </p>
              </div>
              <input type="submit" class="button is-primary" value="Save" />
            </form>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column">
          <h1 class="subtitle">
            Edit Description
          </h1>
          <div class="box">
            <form action="{% url 'users:edit_description' edit_user.id %}" method="POST">
              {% csrf_token %}
              <div class="field">
                <div class="control">
                  <textarea class="textarea" placeholder="e.g. Description"
                    name="description">{{ edit_user.description }}</textarea>
                </div>
                </br>
                <input type="submit" class="button is-primary" value="Save" />
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
</body>

</html>

apps/main/templates/main/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>User Dashboard!</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'main/styles/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}

    <section class="section">
      <h1 class="subtitle">
        Welcome to the Test
      </h1>
      <p>
        We're going to build a cool application using a MVC framework! This application
        was built with the Village88 folks!
      </p>
      <div class="box">
        <p class="">Manage Users</p>
        <p>Using this application, you'll learn how to add, remove, and edit users for the application</p>
      </div>
      <div class="box">
        <p class="">Leave messages</p>
        <p>Users will be able to leave a message to another user using this application</p>
      </div>
      <div class="box">
        <p class="">Manage Users</p>
        <p>Admins will be able to edit another user's information (email address, first name, last name, etc)</p>
      </div>
    </section>

  </div>
</body>

</html>

apps/main/templates/main/nav.html
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'users:dashboard' %}">
        <img src="https://image4.owler.com/logo/coding-dojo_owler_20161201_092020_original.png" width="112"
          height="28">
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">

        {% if request.session.user_id %}
        <a class="navbar-item">
          Welcome {{ user.first_name }}
        </a>
        <a href="{% url 'users:edit' user.id %}" class="navbar-item">
          Profile
        </a>
        <a href="{% url 'users:wall' %}" class="navbar-item">
          Messages
        </a>
        {% endif %}
      

        <div class="navbar-item has-dropdown is-hoverable">

        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if request.session.user_id %}
            <a href="{% url 'users:logout' %}" class="button is-gray is-small is-outlined">Logout</a>
            {% else %}
            <a href="{% url 'users:signin' %}" class="button is-gray is-small is-outlined">Sign In</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

apps/main/templates/main/signin.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>User Dashboard!</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'main/styles/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <p class="subtitle">
        Signin
      </p>
      <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <div class="field">
          <label class="label">Email</label>
          <p class="control has-icons-left has-icons-right">
            <input class="input" name="email" type="email" placeholder="Email">
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
            <span class="icon is-small is-right">
              <i class="fas fa-check"></i>
            </span>
          </p>
        </div>
        <div class="field">
          <label class="label">Password</label>
          <p class="control has-icons-left">
            <input class="input" name="password" type="password" placeholder="Password">
            <span class="icon is-small is-left">
              <i class="fas fa-lock"></i>
            </span>
          </p>
        </div>
        <div class="field">
          <p class="control">
            <input class="button is-success" type="submit" value="Login" />
          </p>
        </div>
      </form>

      
    </section>
    <a href="{% url 'users:register' %}" class="button is-text">Don't have an account? Register</a>
  </div>
</body>

</html>

apps/main/templates/main/wall.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello Bulma!</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
  <div class="container">
    {% include 'main/nav.html' %}
    <section class="section">
      <div class="container">
        <form action="{% url 'users:message' %}" method="POST">
          {% csrf_token %}
          <h1 class="subtitle">Post a message</h1>
          <div class="field">
            <div class="control">
              <textarea class="textarea is-primary has-fixed-size" name="message" col="20" rows="2"
                placeholder=""></textarea>
            </div>
          </div>
          <input class="button is-primary is-rounded is-small" type="submit" value="Post a message" />
        </form>

        <section class="section">
          {% for message in messages %}
          <div class="box">
            <article class="media">

              <div class="media-content">
                <div class="content">
                  <p class="has-text-primary">
                    <strong> {{ message.user.first_name }} {{ message.user.last_name }} - </strong>
                    <small> {{ message.created_at }}</small>
                    <br>
                    {{ message.message }}
                  </p>
                </div>

              </div>

            </article>
          </div>
          {% for comment in message.comments.all %}
          <div class="box">
            <article class="media">
              
              <div class="media-content">
                <div class="content">
                  <p class="has-text-info">
                    <strong>{{ comment.user.first_name }} {{ comment.user.last_name }} - </strong>
                    <small>{{ comment.created_at }}</small> <small>31m</small>
                    <br>
                    {{ comment.comment }}
                  </p>
                  <a href="{% url 'users:delete_comment' comment_id=comment.id %}"
                  class="button is-gray is-small is-outlined" type="submit">Delete Comment</a>
                </div>
                
              </div>
            </article>
          </div>
          {% endfor %}

          <form action="{% url 'users:comment' message.id %}" method="POST">
            {% csrf_token %}
            <section class="section">
              <div class="field">
                <div class="control">
                  <textarea class="textarea is-info has-fixed-size" name="comment" rows="1" placeholder=""></textarea>
                </div>
              </div>
              <input class="button is-info is-rounded is-small" type="submit" value="Post a comment" />
            </section>

          </form>
        </section>
        {% endfor %}
      </div>
    </section>
  </div>
</body>

</html>